### ISSUE TITLE
How to  preprocess the Libri2Mix dataset as you described in your README

### ISSUE THREAD

**Issue by xlzhou01** [WangHelin1997/Fast-GeCo#1]
Could you please provide the dataset preprocessing script? I currently have the raw Libri2Mix dataset.

**Comment by WangHelin1997** [comment]
As shown in [https://github.com/WangHelin1997/Fast-GeCo?tab=readme-ov-file#data-preparation](https://github.com/WangHelin1997/Fast-GeCo?tab=readme-ov-file#data-preparation), you need to put mixture audio, reference clean audio and estimated audio from SepFormer within a same folder.

**Comment by xlzhou01** [comment]
As described in your paper, I need to first train on the Libri2Mix train-360 noisy dataset using Sepformer, and then separate the speech?

**Comment by WangHelin1997** [comment]
Yes, see [https://github.com/WangHelin1997/Fast-GeCo?tab=readme-ov-file#run-baseline-sepformer](https://github.com/WangHelin1997/Fast-GeCo?tab=readme-ov-file#run-baseline-sepformer) for details
